spring:
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  # 上传文件大小限制
  http.multipart:
      max-file-size: 1KB
      max-request-size: 1KB
      enabled: true

  #配置数据库
#  datasource:
#    url: jdbc:h2:file:~/.h2/filediff;AUTO_SERVER=TRUE
#    driver-class-name: org.h2.Driver
#    username: root
#    password: 123456
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
#  h2.console:
#    settings.web-allow-others: true
#    path: /h2-console
#
#mybatis.configuration.mapUnderscoreToCamelCase: true

# 账户
url:
  petUrl: https://pet-chain.baidu.com/
  codeParseUrl: http://upload.chaojiying.net/
  centerServer: http://127.0.0.1:8081
chaojiyingConfig:
  user:
  pass:
  softId:
  codeType: 1004
  lenMin: 0